version: '3'

services:
  mongodb:
    image : davybello/mongo-replica-set:4.4.8
    volumes:
      - "./docker/.data/mongo1:/var/lib/mongo1"
      - "./docker/.data/mongo2:/var/lib/mongo2"
      - "./docker/.data/mongo3:/var/lib/mongo3"
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:6.5.4
    ports:
      - '9200:9200'
      - '9300:9300'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
